name: connect_pets
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.9.0
  firebase_storage: ^11.6.3
  cloud_firestore: ^4.14.0
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.5
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  shimmer: ^3.0.0
  uuid: ^4.2.2
  mockito: ^5.4.4
  equatable: ^2.0.5
  convex_bottom_bar: ^3.2.0
  image_picker: ^1.0.7
  gradient_borders: ^1.0.0
  mask_text_input_formatter: ^2.8.0
  whatsapp_unilink: ^2.1.0
  url_launcher: ^6.2.4
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tienne
      fonts:
        - asset: assets/fonts/Tienne-Regular.ttf
  # - family: Trajan Pro
  #   fonts:
  #    - asset: fonts/TrajanPro.ttf
  #    - asset: fonts/TrajanPro_Bold.ttf
  #      weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
