// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const apiKeyAndroid = String.fromEnvironment('APIKEY_FIREBASE_ANDROID');
const apiKeyIos = String.fromEnvironment('APIKEY_FIREBASE_IOS');

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: apiKeyAndroid,
    appId: '1:617366137822:android:5b001544a96da9280c4b4f',
    messagingSenderId: '617366137822',
    projectId: 'connect-pets-ee1fc',
    storageBucket: 'connect-pets-ee1fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKeyIos,
    appId: '1:617366137822:ios:174c01cfacb9dd250c4b4f',
    messagingSenderId: '617366137822',
    projectId: 'connect-pets-ee1fc',
    storageBucket: 'connect-pets-ee1fc.appspot.com',
    iosClientId:
        '617366137822-pb0rhi8emtnlavcjvgtcvgvfik3g9h3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectPets',
  );
}
